//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsTag.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TitleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LetsTag.Resources.TitleStrings", typeof(TitleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Movie: The Game: The Application.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag 215.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace Tagger.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Version.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Version.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of Tags.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocarina of Tags.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Fusion.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag&apos;s Curse.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag&apos;s Quest.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Adventure of Tag.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging Evolved.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags of the Patriots.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags of Liberty.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Eater.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship Edition.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Strike.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaiden.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tag of Great Intention.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Legacy of Great Tagging.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challange of the Taggers.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend of the Seven Tags.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tag Within.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Update.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii Edition.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Crappy PSP Port.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Crippled PSP Port.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mediocre PSP Port.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait of Tags.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags of Sorrow.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symphony of the Tags.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmony of Tags.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle of the Tags.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tags of Time.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender of the Tags.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the Tag.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag to the Past.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag&apos;s Awakening.
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Tag Story Complete.
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal Tag.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piano Collections.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Edition.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lost Tags.
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag&apos;s Kong Quest.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Tagging Action.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diddy&apos;s Tag Quest.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twilight Tag.
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majora&apos;s Tag.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Concert.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD Remix.
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrath of the Tag King.
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of Taggening.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Thousand-Year Tag.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags in Time.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Tags Adventures.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Espionage Tagging.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the Olympic Games.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape from Tagger Bay.
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode 1.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Warfare.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Tagging.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
